### ISSUE TITLE
容量削減

### ISSUE THREAD

**Issue by Mofa-Xingche** [tsukumijima/Style-Bert-VITS2#2]
すみません失礼します
１　onnxruntime
２　onnxruntime-directml;
この二つでwindowsのcpu onnxとGPU onnxのみの最小の音声合成環境をsbv2で作ろうと思うのですが
音声合成しかしない場合、requirement.txtの内容はどこまで削減できるでしょうか？
requirments-inferでも配布アプリが8GBとかになってしまっていて大変です
感情スタイル指定の音声合成のみ行います、音低指定とかfastsereverとかは使いません
onnx推論だからtorch系全部要らなくてもいいのでしょうか

<pre>
accelerate
cmudict
cn2an
        # faster-whisper==0.10.1
g2p_en
GPUtil
gradio>=4.32
jieba
         # librosa==0.9.2
loguru
nltk<=3.8.1
num2words
numpy<2
onnx
onnxruntime
onnxruntime-directml; sys_platform == 'win32'
onnxruntime-gpu; sys_platform != 'darwin'
onnxsim
# protobuf==4.25
psutil
# punctuators
pyannote.audio>=3.1.0
# pyloudnorm
pyopenjtalk-plus
pypinyin
pyworld-prebuilt
# stable_ts
# tensorboard
torch
torchaudio
transformers
umap-learn
</pre>

あ、それかもしこういうrequirment.txtで大量にインスコして環境構築する感じじゃなくて、pip install style_bert_vits2したときの環境って
onnxruntime
onnxruntime-directml; sys_platform == 'win32'

の推論は動くのでしょうか
あとできればpyopenjtalk-plusも使いたいですけれど、pipの公式サイト見るとpipの style_bert_vits2って2.50で更新止まってるので色々機能抜けてそうで心配です

**Comment by tsukumijima** [comment]
このリポジトリは個人的なフォークであり、詳細をお答えすることはできません。
注意点として、「PyPI に公開されている style-bert-vits2 パッケージは長らくメンテナンスされておらず、最新版を使うには litagin02/Style-Bert-VITS2 パッケージから直接インストールする必要がある」ことはお伝えしておきます。
また、こうした質問は本家リポジトリの方へお願いいたします。
